notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
language: python
cache: pip
python:
- 2.7
- 3.5
- 3.6
install:
- pip install -r requirements-dev.txt
- pip install .
deploy:
  provider: pypi
  user: lkostka
  password: $PYPI_PASS
  on:
    tags: true
    branch: master
    python: '3.6'
script:
- py.test
- pylama .
